[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
async-std = "1.13"
bevy = { version = "0.15", features = ["default", "serialize"] }
bevy-inspector-egui = "0.28"
bevy_egui = "0.31"
const_format = "0.2"
egui_dock = "0.14"
egui-file-dialog = "0.7"
ron = "0.8"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
