[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
async-std = "1.13"
bevy = { version = "0.15", features = ["default", "serialize"] }
bevy-inspector-egui = "0.28"
bevy_egui = { version = "0.31", features = ["immutable_ctx"] }
const_format = "0.2"
derive_more = "1"
egui-file-dialog = "0.7"
egui_dock = { version = "0.14", features = ["serde"] }
leafwing-input-manager = "0.16"
parking_lot = "0.12"
platform-dirs = "0.3"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
uuid = { version = "1.11", features = ["serde"] }
