[package]
name = "persistent-id"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }
