[package]
name = "beditor-lib"
version = "0.1.0"
edition = "2024"

[dependencies]

# exports
bevy_egui = { workspace = true }
macros = { workspace = true }
persistent-id = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["serde"] }

# internal
async-std = { workspace = true }
bevy = { workspace = true, features = ["default", "serialize", "bevy_remote"] }
bevy-inspector-egui = { workspace = true, features = ["highlight_changes"] }
derive-new = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
dotenvy = { workspace = true }
egui = { workspace = true }
egui-file-dialog = { workspace = true }
egui_dock = { workspace = true, features = ["serde"] }
egui_phosphor_icons = { workspace = true }
egui_tracing = { workspace = true }
include_dir = { workspace = true }
itertools = { workspace = true }
leafwing-input-manager = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
platform-dirs = { workspace = true }
postcard = { workspace = true, features = ["use-std"] }
profiling = { workspace = true, features = ["profile-with-tracing"] }
ron = { workspace = true }
rusqlite = { workspace = true, features = ["bundled"] }
rusqlite_migration = { workspace = true, features = ["from-directory"] }
serde_json = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
variadics_please = { workspace = true }


[features]
profiling = ["bevy/trace_tracy"]
watch = ["bevy/file_watcher"]
